version: '3'
services:
  clash:
    image: bohong65/clash-docker:latest
    container_name: clash-docker
    network_mode: bridge
    restart: unless-stopped
    ports:
      - '7890:7890' # Mixed Port
      - '901:901' # External Controller (Restful API)
    volumes:
      - './clash/config:/clash/config'
