# https://github.com/uxber
#
# Description: Build DockerImages using GitHub Actions
#

name: Clash Premium

on:
  push:
    tags:
      - "*"

env:
    # github.repository as <account>/<repo>
    IMAGE_NAME: ${{ github.repository }}
    IMAGE_PLATFORM: 'linux/arm64,linux/amd64'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Buildx

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Set up QEMU Simulator
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag

      - name: Premium version
        id: tag
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Build and Publish image
        uses: docker/build-push-action@master
        with:
          context: docker
          platforms: ${{ env.IMAGE_PLATFORM }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CLASH_PREMIUM_VERSION=${{ steps.tag.outputs.version }}
