# https://github.com/xtoys
#
# Description: Build DockerImages using GitHub Actions
#

name: Clash Premium

on:
  workflow_dispatch:
    inputs:
      img:
        description: 'DockerImage Name'
        required: true
        default: 'clash'
      core:
        description: 'PremiumCore Version'
        required: true
        default: ''
      platform:
        description: 'DockerImage Platform'
        required: true
        default: 'linux/arm64,linux/amd64'
        type: choice
        options:
          - 'linux/arm64,linux/amd64'
          - 'linux/arm64'
          - 'linux/amd64'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker Build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup QEMU Simulator
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish image
        uses: docker/build-push-action@v3
        with:
          context: docker
          platforms: ${{ github.event.inputs.platform }}
          push: true
          build-args: |
            CLASH_PREMIUM_VERSION=${{ github.event.inputs.core }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.img }}:${{ github.event.inputs.core }}
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.img }}:latest
